export default chapterData = [
  {
    title: 'Introducing React Native',
    description: 'Learn why React Native is the best platform for building rich and robust native apps on iOS and Android with Javascript',
    contentPath: 'chapter_1_introducing_react_native.md',
    path: '/chapters/introducing-react-native',
    subscriberChapter: false,
    unfinishedChapter: false,
  },
  {
    title: 'Getting Started',
    description: 'Read about the basics of getting React Native set up on your machine and how the framework is structured',
    contentPath: 'chapter_2_getting_started.md',
    path: '/chapters/getting-started',
    subscriberChapter: false,
    unfinishedChapter: false,
  },
  {
    title: 'The Beginnings of an App',
    description: 'Understand the basics of structuring an app in React Native, including building simple views and routing',
    contentPath: 'chapter_3_the_beginnings_of_an_app.md',
    path: '/chapters/the-beginnings-of-an-app',
    subscriberChapter: false,
    unfinishedChapter: false,
  },
  {
    title: 'Basic TabBar Navigation',
    description: 'Learn to configure basic tabbar navigation in your app to separate your primary views',
    contentPath: 'chapter_4_basic_tabbar_navigation.md',
    path: '/chapters/basic-tabbar-navigation',
    subscriberChapter: false,
    unfinishedChapter: false,
  },
  {
    title: 'User Accounts, Part 1',
    contentPath: 'chapter_5_user_accounts_part_1.md',
    path: '/chapters/user-accounts-part-1',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'User Accounts, Part 2',
    contentPath: 'chapter_6_user_accounts_part_2.md',
    path: '/chapters/user-accounts-part-2',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Building a Messaging System',
    contentPath: 'chapter_7_establishing_a_database_schema.md',
    path: '/chapters/building-messaging',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Creating Groups',
    contentPath: 'chapter_8_creating_groups.md',
    path: '/chapters/adding-groups',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Creating Events',
    contentPath: 'chapter_9_creating_events.md',
    path: '/chapters/adding-events',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Swipe Left, Swipe Right',
    contentPath: 'chapter_10_swipe_left,_swipe_right.md',
    path: '/chapter/swipe-actions',
    subscriberChapter: true,
    unfinishedChapter: false
  },
  {
    title: 'Building a Notification System',
    contentPath: 'chapter_10_building_a_calendar_view.md',
    path: '/chapters/activity-view',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Building a Calendar View',
    contentPath: 'chapter_11_building_an_activity_view.md',
    path: '/chapters/calendar-view',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Final Touches',
    contentPath: 'chapter_12_final_touches.md',
    path: '/chapters/final-touches',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Understanding ES6 JavaScript with React Native',
    contentPath: 'chapter_13_understanding_es6_with_react_native.md',
    path: '/chapters/understanding-es6',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Deploying an API',
    contentPath: 'chapter_16_deployment.md',
    path: '/chapters/api-deployment',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
  {
    title: 'Deploying to the App Store',
    contentPath: 'chapter_15_deploying_to_the_app_store.md',
    path: '/chapters/app-store-deployment',
    subscriberChapter: true,
    unfinishedChapter: true,
  },
  {
    title: 'Deploying to the Google Play Store',
    contentPath: 'chapter_16_deploying_to_the_google_play_store.md',
    path: '/chapters/google-play-deployment',
    subscriberChapter: true,
    unfinishedChapter: true,
  },
  {
    title: 'Mobile Design Principles',
    contentPath: 'chapter_17_mobile_design_principles.md',
    path: '/chapters/mobile-design',
    subscriberChapter: true,
    unfinishedChapter: true,
  },
  {
    title: 'Adding Redux to Your App',
    contentPath: 'chapter_18_adding_redux_to_your_app.md',
    path: '/chapters/adding-redux',
    subscriberChapter: true,
    unfinishedChapter: false,
  },
]
